{
 "title": "Postgres Table View",
 "panels": [
  {
   "title": "Machine Assembly Robot Data",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM machine_assembly_robot LIMIT 50 "
    }
   ]
  },
  {
   "title": "Machine CNC Data",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM machine_cnc LIMIT 50 "
    }
   ]
  },
  {
   "title": "Machine Packaging Data",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM machine_packaging LIMIT 50 "
    }
   ]
  }
 ]
}