version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"


  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"


  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - machine_cnc
      - machine_assembly_robot


  machine_cnc:
    build: ./backend/machine_cnc
    depends_on:
      - kafka
      - postgres
    ports:
      - "5001:5001"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    restart: on-failure


  machine_assembly_robot:
    build: ./backend/machine_assembly_robot
    depends_on:
      - kafka
      - postgres
      - machine_cnc
    ports:
      - "5002:5002"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    restart: on-failure


  machine_packaging:
    build: ./backend/machine_packaging
    depends_on:
      - kafka
      - postgres
      - machine_cnc
      - machine_assembly_robot
    ports:
      - "5003:5003"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    restart: on-failure


  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql


  grafana:
    image: grafana/grafana
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning


volumes:
  postgres-data:
  grafana-storage:
