apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    isDefault: true
    editable: true
    url: postgres:5432
    database: mydb
    user: user
    secureJsonData:
      password: password
    jsonData:
      sslmode: disable
